# Generated by Django 5.2.4 on 2025-07-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentences', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Testimonial/%Y/%m/%d')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
