# Generated by Django 5.2.4 on 2025-07-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='Overview/%Y/%m/%d')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Overview',
                'verbose_name_plural': 'Overviews',
            },
        ),
    ]
