# Generated by Django 5.2.4 on 2025-07-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Home/%Y/%m/%d')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='Home/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
            },
        ),
    ]
